services:
  webapp:
    build: 
      context: .           # Current directory containing Dockerfile and source files
      dockerfile: Dockerfile
    volumes:
      - .:/code           # Optional: Mount current directory for development
    ports:
      - "8000:8000"    
  
  pgdatabase:
    image: postgres:18
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "hard_drive"
    volumes:
      - "hard_drive_postgres_data:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"
    networks:
      - pg-network

volumes:
  hard_drive_postgres_data:
  pgadmin_data:

networks:
  pg-network:
